### PR TITLE
fix: parquet serializer

### LINKED ISSUE #511: Parquet serializer
The Parquet serializer has two issues. They are illustrated with the following api query

```
https://data.ssb.no/api/pxwebapi/v2/tables/14216/data/?valuecodes[TettSted]=0801  
&valuecodes[ContentsCode]=Areal,Bosatte&valuecodes[Tid]=2025,2024&outputFormat=parquet
```
Resulting Parquet

år | timestamp | tettsted | ContentsCode_Areal | ContentsCode_Areal_symbol | ContentsCode_Bosatte | ContentsCode_Bosatte_symbol
-- | -- | -- | -- | -- | -- | --
2024 | 2024-01-01T00:00:00.000 | 0801 | 275,87 |   | 1110887 |  
2024 | 2024-01-01T00:00:00.000 | 0801 | 1110887 |   | 276,3 |  
2025 | 2025-01-01T00:00:00.000 | 0801 | 276,3 |   | 1098061 |  
2025 | 2025-01-01T00:00:00.000 | 0801 | 1098061 |   | 1098061 |  

1. Selecting two or more contents (Areal and Bosatte) creates to many rows in the resulting parquet file, in this case there should have been two rows
2. Selecting years `2025,2024` is not the same as selecting `2024,2025`. In this case the the first row is actually the 2025 figures. The reason for this is that the parquet seralizer uses `TIMEVAL` and from the px output below we see that TIMVAL is the same when swapping the years. The api does not sort any valuecodes. This is intentional in the new api.

```sh
$ curl "https://data.ssb.no/api/pxwebapi/v2/tables/14216/data/?valuecodes%5bTettSted%5d=0801&valuecodes%5bContentsCode%5d=Areal,Bosatte&valuecodes%5bTid%5d=2025,2024&outputFormat=px" -s -i | grep -E '(TIMEVAL|CODES|VALUES)'
VALUES("tettsted")="Oslo";
VALUES("statistikkvariabel")="Areal av tettsted (km?)","Bosatte";
VALUES("år")="2025","2024";
TIMEVAL("år")=TLIST(A1),"2024","2025";
CODES("tettsted")="0801";
CODES("statistikkvariabel")="Areal","Bosatte";
CODES("år")="2025","2024";
```

```sh
$ curl "https://data.ssb.no/api/pxwebapi/v2/tables/14216/data/?valuecodes%5bTettSted%5d=0801&valuecodes%5bContentsCode%5d=Areal,Bosatte&valuecodes%5bTid%5d=2024,2025&outputFormat=px" -s -i | grep -E '(TIMEVAL|CODES|VALUES)'
VALUES("tettsted")="Oslo";
VALUES("statistikkvariabel")="Areal av tettsted (km?)","Bosatte";
VALUES("år")="2024","2025";
TIMEVAL("år")=TLIST(A1),"2024","2025";
CODES("tettsted")="0801";
CODES("statistikkvariabel")="Areal","Bosatte";
CODES("år")="2024","2025";
```

The first issue with to many rows is a clear bug. I have changed the tests and will try and fix the bug in https://github.com/PxTools/PCAxis.Serializers/pull/181

For the second issue it is not clear if the bug is in the parquet serializer or in the PxWebApi for not sorting time in ascending order?

Is [this](https://data.ssb.no/api/pxwebapi/v2/tables/14216/data/?valuecodes%5bTettSted%5d=0801&valuecodes%5bContentsCode%5d=Areal,Bosatte&valuecodes%5bTid%5d=2024,2025&outputFormat=px) a valid PX file according to the [TIMEVAL documentation](https://github.com/PxTools/PxFileFormat/blob/main/keywords/TIMEVAL.md)?

### PR DESCRIPTION
**Pull request by trygu**
* Fixes issues related to too many rows when you have more than one content. Tests have been updated to reflect that.
* Fixes issues with wrong time in the Parquet-file when the VALUES order differs from the TIMEVAL order. 

Fixes https://github.com/PxTools/PxWebApi/issues/511

### CODE REVIEW

**Comment by trygu** [comment]
There is still an issue related to Px-files without CODE for Time.. since .TimeValue is missing (or wrong), which makes the datetime creation fail.

**Review by likp — APPROVED** [review]

**Review by likp — CHANGES_REQUESTED** [review]
The test fail, have to be fixed, connected to @trygu comment above.

File: PCAxis.Serializers/Parquet/ParquetBuilder.cs [hunk 1]
```diff
@@ -256,14 +256,12 @@ private void PopulateContentVariableRow(int[] index, int[] variableValueCounts,
...
+
             if (variable.IsTime)
             {
-                // Use the VALUES ordering (Code) for the displayed time value so it
-                // matches the order of the data array. Some PX files have a
-                // different TIMEVAL ordering; using Code ensures consistency with
-                // the data which follows VALUES(...).
-                row[dataFieldIndices[variable.Name]] = value; // Original time-value (from VALUES)
-                row[dataFieldIndices["timestamp"]] = ParseTimeScale(value, variable.TimeScale); // Parsed timestamp
+                value = variable.Values[index[i]].TimeValue;
```
Comment (runejo) [inline PCAxis.Serializers/Parquet/ParquetBuilder.cs]: @trygu why did you add this line again? 
`value = variable.Values[index[i]].TimeValue;`

If I remove it the `14216.parquet` works

```
{"tettsted":"0801","år":"2025","timestamp":1735689600000,"ContentsCode_Areal":275.87,"ContentsCode_Areal_symbol":null,"ContentsCode_Bosatte":1110887,"ContentsCode_Bosatte_symbol":null}
{"tettsted":"0801","år":"2024","timestamp":1704067200000,"ContentsCode_Areal":276.3,"ContentsCode_Areal_symbol":null,"ContentsCode_Bosatte":1098061,"ContentsCode_Bosatte_symbol":null}
```

Image

Comment (runejo) [reply PCAxis.Serializers/Parquet/ParquetBuilder.cs]: I get it, I didn't know that TimeValue looked like `20071` and the Code is `2007K1`

Comment (runejo) [reply PCAxis.Serializers/Parquet/ParquetBuilder.cs]: I can make it work in the ParquetSerilizer using `Code` and `Value`, but the real problem seems to be in Paxiom. `TimeValue` is clearly wrong.  Can we discuss it tomorrow @likp ?

image

Comment (runejo) [reply PCAxis.Serializers/Parquet/ParquetBuilder.cs]: Ok, we discussed it yesterday in our weekly PxWebApi meeting, and we agreed to make it work without looking at TimeValue. I'll commit the fix on this branch now.

**Review by runejo — APPROVED** [review]

**Comment by likp** [comment]
Connected to https://github.com/PxTools/PxWebApi/issues/550

**Review by likp — APPROVED** [review]
